version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg13
    container_name: dungeontalk-postgres
    environment:
      POSTGRES_DB: dungeontalk_rag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dungeontalk_rag"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: